### ISSUE TITLE
ciel::inplace_vector move-assignment discrepancy

### ISSUE THREAD

**Issue by Quuxplusone** [namespaceciel/ciellab#5]
```
#include <cstdio>
#include <tuple>
#include <utility>

#include <absl/container/inlined_vector.h> // git@github.com:abseil/abseil-cpp
#include <array>
#include <boost/container/static_vector.hpp>
#include <ciel/inplace_vector.hpp>
#include <inplace_vector>  // https://github.com/llvm/llvm-project/pull/105981
#include <sg14/inplace_vector.h> // git@github.com:Quuxplusone/SG14

int main() {
  using AsgnThru = std::tuple<int&>;
  {
    int x = 1, y = 2, z = 3, w = 4;
    std::array<AsgnThru, 2> v1 = { std::tie(x), std::tie(y) };
    std::array<AsgnThru, 2> v2 = { std::tie(z), std::tie(w) };
    v1 = std::move(v2);
    printf("%d %d %d %d\n", x, y, z, w);  // 3 4 3 4
  }
  {
    int x = 1, y = 2, z = 3, w = 4;
    sg14::inplace_vector<AsgnThru, 2> v1 = { std::tie(x), std::tie(y) };
    sg14::inplace_vector<AsgnThru, 2> v2 = { std::tie(z), std::tie(w) };
    v1 = std::move(v2);
    printf("%d %d %d %d\n", x, y, z, w);  // 3 4 3 4
  }
  {
    int x = 1, y = 2, z = 3, w = 4;
    std::inplace_vector<AsgnThru, 2> v1 = { std::tie(x), std::tie(y) };
    std::inplace_vector<AsgnThru, 2> v2 = { std::tie(z), std::tie(w) };
    v1 = std::move(v2);
    printf("%d %d %d %d\n", x, y, z, w);  // 3 4 3 4
  }
  {
    int x = 1, y = 2, z = 3, w = 4;
    boost::container::static_vector<AsgnThru, 2> v1 = { std::tie(x), std::tie(y) };
    boost::container::static_vector<AsgnThru, 2> v2 = { std::tie(z), std::tie(w) };
    v1 = std::move(v2);
    printf("%d %d %d %d\n", x, y, z, w);  // 3 4 3 4
  }
  {
    int x = 1, y = 2, z = 3, w = 4;
    absl::InlinedVector<AsgnThru, 2> v1 = { std::tie(x), std::tie(y) };
    absl::InlinedVector<AsgnThru, 2> v2 = { std::tie(z), std::tie(w) };
    v1 = std::move(v2);
    printf("%d %d %d %d\n", x, y, z, w);  // 3 4 3 4
  }
  {
    int x = 1, y = 2, z = 3, w = 4;
    ciel::inplace_vector<AsgnThru, 2> v1 = { std::tie(x), std::tie(y) };
    ciel::inplace_vector<AsgnThru, 2> v2 = { std::tie(z), std::tie(w) };
    v1 = std::move(v2);
    printf("%d %d %d %d\n", x, y, z, w);  // 1 2 3 4
  }
}
```

For all of `std::array`, C++26 `std::inplace_vector`, `sg14::inplace_vector`, `absl::InlinedVector`, and `boost::static_vector`, vector assignment will assign each of the elements, which for `tuple<int&>` means assign-through: in this example assign-through changes the values of `x` and `y`, it does not rebind the references to `z` and `w`.

`ciel::inplace_vector` doesn't follow the herd here. I suspect this is _probably_ unintentional, caused by (what I believe to be) a bug in your `ciel::is_trivially_relocatable` trait. You allow `ciel::is_trivially_relocatable<T>` to be true as long as `is_trivially_move_constructible<T>` is true — but you fail to check that `T` is also trivially move assignable, copy constructible, and copy assignable. (You do implicitly check that it's trivially destructible, due to [a quirk of the standard `_constructible` traits](https://en.cppreference.com/w/cpp/types/is_constructible#Notes); so that part is OK.)

So what's currently happening here is that ciel sees `ciel::is_trivially_relocatable<tuple<int&>>::value`, and then assumes that it can use memcpy to implement `inplace_vector<tuple<int&>>` assignment. The conclusion is valid, but the premise is false.

In P1144 terminology, the optimization you're trying to do here can be done only for "trivially relocatable" types, and `tuple<int&>` is "not trivially relocatable."
In P2786R7 terminology, the optimization can be done only for types that are "both trivially relocatable and replaceable," and `tuple<int&>` is "trivially relocatable but not replaceable."

**Comment by namespaceciel** [comment]
Thank you very much for your guidance! It took me quite a while to figure out what happened.

> You allow `ciel::is_trivially_relocatable<T>` to be true as long as `is_trivially_move_constructible<T>` is true — but you fail to check that `T` is also trivially move assignable, copy constructible, and copy assignable.

However, even if `T` is `trivially_[copy/move]_[constructible/assignable]`, that won’t be sufficient since reference types satisfy all these requirements but they are not `trivially copyable` as they are neither scalar types nor class types.
And in both [LLVM's](https://github.com/llvm/llvm-project/blob/ceaf6e912a846b88f19df682c6bdbe9516be04e9/libcxx/include/tuple#L552) and my `is_trivially_relocatable` trait, the partial specialization for `tuple` states that `tuple` is `trivially relocatable` if all its components are.
Therefore, I will stick with `std::is_trivially_copyable`.

This also reminds me of the implementations of `swap` and `vector::assign`.
The behavior of `vector::assign` differs depending on whether the new size exceeds its capacity.
Some naive implementations, where `assign(N, value)` is equivalent to `clear()` followed by N calls to `emplace_back(value)`, are totally incorrect either.

[Fixed commit](https://github.com/namespaceciel/ciellab/commit/c6c38728ce0f58b43c9b8b678b8ec4de634924f8)
